#!/bin/sh

code --install-extension alexcvzz.vscode-sqlite
code --install-extension arcanis.vscode-zipfs
code --install-extension csholmq.excel-to-markdown-table
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fernandoescolar.vscode-solution-explorer
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension ghmcadams.lintlens
code --install-extension gitpod.gitpod-desktop
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension James-Yu.latex-workshop
code --install-extension kavod-io.vscode-jest-test-adapter
code --install-extension lextudio.restructuredtext
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-mssql.mssql
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension Orta.vscode-jest
code --install-extension pflannery.vscode-versionlens
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension Roshan.ulka-language-support
code --install-extension silvenon.mdx
code --install-extension SonarSource.sonarlint-vscode
code --install-extension tomoki1207.pdf
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vsls-contrib.gistfs
code --install-extension wayou.vscode-todo-highlight